

CREATE DATABASE drum;

	CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(500) NOT NULL,
  image VARCHAR(500)
);
 
CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  brand VARCHAR(45) NOT NULL,
  description VARCHAR(500) NOT NULL,
  image VARCHAR(45) NOT NULL,
  price INT NOT NULL,
  create_by INT NOT NULL,
  CONSTRAINT create_by
    FOREIGN KEY (create_by)
    REFERENCES users (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
		);
 